
package test.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@javax.jws.WebService(name = "WebService", targetNamespace = "http://webservice.test/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://webservice.test/", className = "test.webservice.client.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://webservice.test/", className = "test.webservice.client.TestResponse")
    public String test();

}
