
package test.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@HandlerChain(file="client-handler-chain.xml")
@WebServiceClient(name = "WebServiceService", targetNamespace = "http://webservice.test/", wsdlLocation = "http://192.168.0.119:8081/ws/test?wsdl")
public class WebServiceService
    extends Service
{

    private final static URL WEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(test.webservice.client.WebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = test.webservice.client.WebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.0.119:8081/ws/test?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.0.119:8081/ws/test?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public WebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceService() {
        super(WEBSERVICESERVICE_WSDL_LOCATION, new QName("http://webservice.test/", "WebServiceService"));
    }

    /**
     * 
     * @return
     *     returns WebService
     */
    @WebEndpoint(name = "WebServicePort")
    public WebService getWebServicePort() {
        return super.getPort(new QName("http://webservice.test/", "WebServicePort"), WebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService
     */
    @WebEndpoint(name = "WebServicePort")
    public WebService getWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.test/", "WebServicePort"), WebService.class, features);
    }

}
